version: '3'

services:
  fpm:
    build:
      dockerfile: docker/prod/fpm/Dockerfile
      context: .
      args:
        - BASE_FPM_IMAGE=akeneo-fpm-secret
    image: akeneo-docker-fpm
    container_name: akeneo-docker-fpm
    networks:
      - akeneo

  mysql:
    image: 'mysql:5.7'
    container_name: akeneo-docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'akeneo_pim'
      MYSQL_PASSWORD: 'akeneo_pim'
      MYSQL_DATABASE: 'akeneo_pim'
    networks:
      - akeneo

  httpd:
    build:
      dockerfile: docker/prod/httpd/Dockerfile
      context: .
      args:
        - BASE_SECRET_WEBSERVER_IMAGE=secret-web-server
    image: akeneo-docker-httpd
    container_name: akeneo-docker-httpd
    ports:
      - '80:80'
    networks:
      - akeneo

networks:
  akeneo:
