version: '3'

services:
  fpm:
    image: emotionio/akeneo:ce-3.2-fpm
    volumes:
      - 'web-media-cache:/srv/pim/web/media/cache'
      - 'file_storage:/srv/pim/app/file_storage'
      - 'archives:/srv/pim/app/archive'
      - 'uploads:/srv/pim/app/uploads'
    networks:
      - akeneo

  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    networks:
      - akeneo

  db-tasks:
    image: emotionio/akeneo:ce-3.2-db-tasks
    volumes:
      - 'file_storage:/srv/pim/app/file_storage'
      - 'archives:/srv/pim/app/archive'
    networks:
      - akeneo

  httpd:
    image: emotionio/akeneo:ce-3.2-httpd
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'web-media-cache:/srv/pim/web/media/cache:ro'
    networks:
      - akeneo

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4'
    environment:
      ES_JAVA_OPTS: '${ES_JAVA_OPTS:--Xms512m -Xmx512m}'
      discovery.type: 'single-node'
    volumes:
      - 'es-data:/usr/share/elasticsearch/data'
    networks:
      - akeneo

  object-storage:
    image: 'minio/minio'
    entrypoint: '/bin/sh -c "mkdir -p /data/archive /data/catalog/ /data/jobs && minio server /data"'
    environment:
      MINIO_ACCESS_KEY: '${MINIO_ACCESS_KEY}'
      MINIO_SECRET_KEY: '${MINIO_SECRET_KEY}'
    networks:
      - akeneo

  daemon:
    image: emotionio/akeneo:ce-3.2-daemon
    volumes:
      - 'file_storage:/srv/pim/app/file_storage'
      - 'archives:/srv/pim/app/archive'
      - 'uploads:/srv/pim/app/uploads'
    networks:
      - akeneo

volumes:
  web-media-cache:
  mysql-data:
  es-data:
  file_storage:
  archives:
  uploads:

networks:
  akeneo:
