<?php /** @noinspection ALL */

namespace Pim\Upgrade\Schema;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20200224084402_mappings extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE oro_config_value (id INT AUTO_INCREMENT NOT NULL, config_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, section VARCHAR(50) DEFAULT NULL, value LONGTEXT DEFAULT NULL, INDEX IDX_DAF6DF5524DB0683 (config_id), UNIQUE INDEX CONFIG_VALUE_UQ_ENTITY (name, section, config_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_config (id INT AUTO_INCREMENT NOT NULL, entity VARCHAR(255) DEFAULT NULL, record_id INT DEFAULT NULL, UNIQUE INDEX CONFIG_UQ_ENTITY (entity, record_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_api_refresh_token (id INT AUTO_INCREMENT NOT NULL, client INT DEFAULT NULL, user INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_264A45105F37A13B (token), INDEX IDX_264A4510C7440455 (client), INDEX IDX_264A45108D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_api_client (id INT AUTO_INCREMENT NOT NULL, random_id VARCHAR(255) NOT NULL, redirect_uris LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', secret VARCHAR(255) NOT NULL, allowed_grant_types LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_api_auth_code (id INT AUTO_INCREMENT NOT NULL, token VARCHAR(255) NOT NULL, redirect_uri LONGTEXT NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_AD5DC7C65F37A13B (token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_api_access_token (id INT AUTO_INCREMENT NOT NULL, client INT DEFAULT NULL, user INT DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at INT DEFAULT NULL, scope VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_BD5E40235F37A13B (token), INDEX IDX_BD5E4023C7440455 (client), INDEX IDX_BD5E40238D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_datagrid_view (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, label VARCHAR(100) NOT NULL, type VARCHAR(10) DEFAULT NULL, datagrid_alias VARCHAR(255) NOT NULL, columns LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', filters LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_B56B38F1EA750E8 (label), INDEX IDX_B56B38F17E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_notification_notification (id INT AUTO_INCREMENT NOT NULL, route VARCHAR(255) DEFAULT NULL, routeParams LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', message VARCHAR(255) NOT NULL, messageParams LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', comment VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', type VARCHAR(20) NOT NULL, context LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_notification_user_notification (id INT AUTO_INCREMENT NOT NULL, notification INT DEFAULT NULL, user INT DEFAULT NULL, viewed TINYINT(1) NOT NULL, INDEX IDX_342AA855BF5476CA (notification), INDEX IDX_342AA8558D93D649 (user), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_versioning_version (id INT AUTO_INCREMENT NOT NULL, author VARCHAR(255) NOT NULL, resource_name VARCHAR(255) NOT NULL, resource_id VARCHAR(24) NOT NULL, snapshot LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', changeset LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', context VARCHAR(255) DEFAULT NULL, version INT DEFAULT NULL, logged_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', pending TINYINT(1) NOT NULL, INDEX resource_name_resource_id_idx (resource_name, resource_id), INDEX resource_name_idx (resource_name), INDEX pending_idx (pending), INDEX version_idx (version), INDEX logged_at_idx (logged_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_batch_job_execution (id INT AUTO_INCREMENT NOT NULL, job_instance_id INT NOT NULL, pid INT DEFAULT NULL, user VARCHAR(255) DEFAULT NULL, status INT NOT NULL, start_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', end_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', create_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', updated_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', health_check_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', exit_code VARCHAR(255) DEFAULT NULL, exit_description LONGTEXT DEFAULT NULL, failure_exceptions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', log_file VARCHAR(255) DEFAULT NULL, raw_parameters JSON NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_62738477593D6954 (job_instance_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_batch_job_instance (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(255) DEFAULT NULL, job_name VARCHAR(50) NOT NULL, status INT NOT NULL, connector VARCHAR(255) NOT NULL, raw_parameters LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', type VARCHAR(255) NOT NULL, UNIQUE INDEX searchunique_idx (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_batch_step_execution (id INT AUTO_INCREMENT NOT NULL, job_execution_id INT DEFAULT NULL, step_name VARCHAR(100) DEFAULT NULL, status INT NOT NULL, read_count INT NOT NULL, write_count INT NOT NULL, filter_count INT NOT NULL, start_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', end_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', exit_code VARCHAR(255) DEFAULT NULL, exit_description LONGTEXT DEFAULT NULL, terminate_only TINYINT(1) DEFAULT NULL, failure_exceptions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', errors LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', summary LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_BDE7D0925871C06B (job_execution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_batch_warning (id INT AUTO_INCREMENT NOT NULL, step_execution_id INT DEFAULT NULL, reason LONGTEXT DEFAULT NULL, reason_parameters LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', item LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_8EE0AE736C7DA296 (step_execution_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_batch_job_execution_queue (id INT AUTO_INCREMENT NOT NULL, job_execution_id INT DEFAULT NULL, options JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', consumer VARCHAR(255) DEFAULT NULL, create_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', updated_time DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE akeneo_file_storage_file_info (id INT AUTO_INCREMENT NOT NULL, file_key VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(255) NOT NULL, size INT DEFAULT NULL, extension VARCHAR(10) NOT NULL, hash VARCHAR(100) DEFAULT NULL, storage VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F19B3719A5D32530 (file_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_access_group (id SMALLINT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_FEF9EDB75E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_user_access_group_role (group_id SMALLINT NOT NULL, role_id SMALLINT NOT NULL, INDEX IDX_E7E7E38EFE54D947 (group_id), INDEX IDX_E7E7E38ED60322AC (role_id), PRIMARY KEY(group_id, role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_access_role (id SMALLINT AUTO_INCREMENT NOT NULL, role VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_673F65E757698A6A (role), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_user (id INT AUTO_INCREMENT NOT NULL, file_info_id INT DEFAULT NULL, ui_locale_id INT NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, name_prefix VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, name_suffix VARCHAR(255) DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) DEFAULT \'1\' NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', last_login DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', login_count INT UNSIGNED DEFAULT 0 NOT NULL, createdAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updatedAt DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', product_grid_filters JSON DEFAULT NULL COMMENT \'(DC2Type:json_array)\', emailNotifications TINYINT(1) DEFAULT \'0\' NOT NULL, phone VARCHAR(20) DEFAULT NULL, timezone VARCHAR(30) NOT NULL, properties JSON NOT NULL COMMENT \'(DC2Type:json_array)\', catalogLocale_id INT DEFAULT NULL, catalogScope_id INT DEFAULT NULL, defaultTree_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_F82840BCF85E0677 (username), UNIQUE INDEX UNIQ_F82840BCE7927C74 (email), UNIQUE INDEX UNIQ_F82840BC6ED78C3 (file_info_id), INDEX IDX_F82840BC7BBFC60C (catalogLocale_id), INDEX IDX_F82840BCA7EA8E8C (ui_locale_id), INDEX IDX_F82840BCEAA72736 (catalogScope_id), INDEX IDX_F82840BCD654B1EE (defaultTree_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_user_access_role (user_id INT NOT NULL, role_id SMALLINT NOT NULL, INDEX IDX_290571BEA76ED395 (user_id), INDEX IDX_290571BED60322AC (role_id), PRIMARY KEY(user_id, role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE oro_user_access_group (user_id INT NOT NULL, group_id SMALLINT NOT NULL, INDEX IDX_EC003EF3A76ED395 (user_id), INDEX IDX_EC003EF3FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_user_default_datagrid_view (user_id INT NOT NULL, view_id INT NOT NULL, INDEX IDX_3CEEC2F2A76ED395 (user_id), INDEX IDX_3CEEC2F231518C7 (view_id), PRIMARY KEY(user_id, view_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_locale (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(20) NOT NULL, is_activated TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_7405C7B177153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_channel (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, code VARCHAR(100) NOT NULL, conversionUnits LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_E07E932A77153098 (code), INDEX IDX_E07E932A12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_channel_currency (channel_id INT NOT NULL, currency_id INT NOT NULL, INDEX IDX_5B55C68472F5A1AA (channel_id), INDEX IDX_5B55C68438248176 (currency_id), PRIMARY KEY(channel_id, currency_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_channel_locale (channel_id INT NOT NULL, locale_id INT NOT NULL, INDEX IDX_D8113CB272F5A1AA (channel_id), INDEX IDX_D8113CB2E559DFD1 (locale_id), PRIMARY KEY(channel_id, locale_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_channel_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_8A91679D7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_currency (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(3) NOT NULL, is_activated TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_5A1712C777153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_product_model (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT \'(DC2Type:native_json)\', created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', root INT NOT NULL, lvl INT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, UNIQUE INDEX UNIQ_5943911E77153098 (code), INDEX IDX_5943911E727ACA70 (parent_id), INDEX IDX_5943911E8A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_category_product_model (product_model_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_62B5D36B2C5DD70 (product_model_id), INDEX IDX_62B5D3612469DE2 (category_id), PRIMARY KEY(product_model_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association (id INT AUTO_INCREMENT NOT NULL, association_type_id INT NOT NULL, owner_id INT NOT NULL, INDEX IDX_CC271001B1E1C39 (association_type_id), INDEX IDX_CC2710017E3C61F9 (owner_id), UNIQUE INDEX locale_foreign_key_idx (owner_id, association_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_group (association_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_E91414DDEFB9C8A5 (association_id), INDEX IDX_E91414DDFE54D947 (group_id), PRIMARY KEY(association_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_product (association_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_3A3A49D4EFB9C8A5 (association_id), INDEX IDX_3A3A49D44584665A (product_id), PRIMARY KEY(association_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_product_model (association_id INT NOT NULL, product_model_id INT NOT NULL, INDEX IDX_378B82C7EFB9C8A5 (association_id), INDEX IDX_378B82C7B2C5DD70 (product_model_id), PRIMARY KEY(association_id, product_model_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_product (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, product_model_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, identifier VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT \'(DC2Type:native_json)\', created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', UNIQUE INDEX UNIQ_91CD19C0772E836A (identifier), INDEX IDX_91CD19C0C35E566A (family_id), INDEX IDX_91CD19C0B2C5DD70 (product_model_id), INDEX IDX_91CD19C08A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_group_product (product_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_7AC0C83A4584665A (product_id), INDEX IDX_7AC0C83AFE54D947 (group_id), PRIMARY KEY(product_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_category_product (product_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_512179C14584665A (product_id), INDEX IDX_512179C112469DE2 (category_id), PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_product_unique_data (id INT AUTO_INCREMENT NOT NULL, product_id INT NOT NULL, attribute_id INT NOT NULL, raw_data VARCHAR(255) NOT NULL, INDEX IDX_E0768BA34584665A (product_id), INDEX IDX_E0768BA3B6E62EFA (attribute_id), UNIQUE INDEX unique_value_idx (attribute_id, raw_data), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_product_model_association (id INT AUTO_INCREMENT NOT NULL, association_type_id INT NOT NULL, owner_id INT NOT NULL, INDEX IDX_F5F4C8CAB1E1C39 (association_type_id), INDEX IDX_F5F4C8CA7E3C61F9 (owner_id), UNIQUE INDEX locale_foreign_key_idx (owner_id, association_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_product_model_to_group (association_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_16EA55AEEFB9C8A5 (association_id), INDEX IDX_16EA55AEFE54D947 (group_id), PRIMARY KEY(association_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_product_model_to_product (association_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_3FF3ED19EFB9C8A5 (association_id), INDEX IDX_3FF3ED194584665A (product_id), PRIMARY KEY(association_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_product_model_to_product_model (association_id INT NOT NULL, product_model_id INT NOT NULL, INDEX IDX_12D4D59CEFB9C8A5 (association_id), INDEX IDX_12D4D59CB2C5DD70 (product_model_id), PRIMARY KEY(association_id, product_model_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_group_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_622D98DB7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_group (id INT AUTO_INCREMENT NOT NULL, type_id INT NOT NULL, code VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_5D6997ED77153098 (code), INDEX IDX_5D6997EDC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_completeness (id INT AUTO_INCREMENT NOT NULL, locale_id INT NOT NULL, channel_id INT NOT NULL, product_id INT NOT NULL, ratio INT NOT NULL, missing_count INT NOT NULL, required_count INT NOT NULL, INDEX IDX_113BA854E559DFD1 (locale_id), INDEX IDX_113BA85472F5A1AA (channel_id), INDEX IDX_113BA8544584665A (product_id), INDEX ratio_idx (ratio), UNIQUE INDEX searchunique_idx (channel_id, locale_id, product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_completeness_missing_attribute (completeness_id INT NOT NULL, missing_attribute_id INT NOT NULL, INDEX IDX_DF61BBD3B640FBA5 (completeness_id), INDEX IDX_DF61BBD3762147F6 (missing_attribute_id), PRIMARY KEY(completeness_id, missing_attribute_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, code VARCHAR(100) NOT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', root INT NOT NULL, lvl INT NOT NULL, lft INT NOT NULL, rgt INT NOT NULL, INDEX IDX_350D8339727ACA70 (parent_id), INDEX left_idx (lft), UNIQUE INDEX pim_category_code_uc (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_category_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_1C0FA6B77E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_comment_comment (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, author_id INT DEFAULT NULL, resource_name VARCHAR(255) NOT NULL, resource_id VARCHAR(24) NOT NULL, body LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', replied_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', INDEX IDX_2A32D03D727ACA70 (parent_id), INDEX IDX_2A32D03DF675F31B (author_id), INDEX resource_name_resource_id_idx (resource_name, resource_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute (id INT AUTO_INCREMENT NOT NULL, group_id INT DEFAULT NULL, sort_order INT NOT NULL, useable_as_grid_filter TINYINT(1) DEFAULT \'0\' NOT NULL, max_characters SMALLINT DEFAULT NULL, validation_rule VARCHAR(10) DEFAULT NULL, validation_regexp VARCHAR(500) DEFAULT NULL, wysiwyg_enabled TINYINT(1) DEFAULT NULL, number_min NUMERIC(14, 4) DEFAULT NULL, number_max NUMERIC(14, 4) DEFAULT NULL, decimals_allowed TINYINT(1) DEFAULT NULL, negative_allowed TINYINT(1) DEFAULT NULL, date_min DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', date_max DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime)\', metric_family VARCHAR(30) DEFAULT NULL, default_metric_unit VARCHAR(30) DEFAULT NULL, max_file_size NUMERIC(6, 2) DEFAULT NULL, allowed_extensions VARCHAR(255) DEFAULT NULL, minimumInputLength SMALLINT DEFAULT NULL, is_required TINYINT(1) NOT NULL, is_unique TINYINT(1) NOT NULL, is_localizable TINYINT(1) NOT NULL, is_scopable TINYINT(1) NOT NULL, code VARCHAR(100) NOT NULL, entity_type VARCHAR(255) NOT NULL, attribute_type VARCHAR(255) NOT NULL, backend_type VARCHAR(255) NOT NULL, properties LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', INDEX IDX_492FD44FFE54D947 (group_id), INDEX searchcode_idx (code), UNIQUE INDEX searchunique_idx (code, entity_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_locale (attribute_id INT NOT NULL, locale_id INT NOT NULL, INDEX IDX_26D2D5D0B6E62EFA (attribute_id), INDEX IDX_26D2D5D0E559DFD1 (locale_id), PRIMARY KEY(attribute_id, locale_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_option (id INT AUTO_INCREMENT NOT NULL, attribute_id INT NOT NULL, code VARCHAR(100) NOT NULL, sort_order INT NOT NULL, INDEX IDX_3DD413F8B6E62EFA (attribute_id), UNIQUE INDEX searchunique_idx (code, attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_variant_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_CB9A96AF7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', UNIQUE INDEX UNIQ_E6CF913A77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_group_type_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_6EF81AEB7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_547C9A607E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_group (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, sort_order INT NOT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', UNIQUE INDEX UNIQ_E299C05E77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_option_value (id INT AUTO_INCREMENT NOT NULL, option_id INT NOT NULL, locale_code VARCHAR(20) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, INDEX IDX_CC4B9A83A7C41D6F (option_id), UNIQUE INDEX searchunique_idx (locale_code, option_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family (id INT AUTO_INCREMENT NOT NULL, label_attribute_id INT DEFAULT NULL, image_attribute_id INT DEFAULT NULL, code VARCHAR(100) NOT NULL, created DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', updated DATETIME NOT NULL COMMENT \'(DC2Type:datetime)\', UNIQUE INDEX UNIQ_9063207277153098 (code), INDEX IDX_90632072E2D3A503 (label_attribute_id), INDEX IDX_90632072BC295696 (image_attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_attribute (family_id INT NOT NULL, attribute_id INT NOT NULL, INDEX IDX_76074884C35E566A (family_id), INDEX IDX_76074884B6E62EFA (attribute_id), PRIMARY KEY(family_id, attribute_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_DBC2A9287E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_requirement (id INT AUTO_INCREMENT NOT NULL, family_id INT NOT NULL, attribute_id INT NOT NULL, channel_id INT NOT NULL, required TINYINT(1) NOT NULL, INDEX IDX_B494B917C35E566A (family_id), INDEX IDX_B494B917B6E62EFA (attribute_id), INDEX IDX_B494B91772F5A1AA (channel_id), UNIQUE INDEX searchunique_idx (channel_id, family_id, attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_variant (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, code VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_FBA5AB4577153098 (code), INDEX IDX_FBA5AB45C35E566A (family_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_variant_has_variant_attribute_sets (family_variant_id INT NOT NULL, variant_attribute_sets_id INT NOT NULL, INDEX IDX_1F4DC7028A37AD0 (family_variant_id), UNIQUE INDEX UNIQ_1F4DC702D8404D (variant_attribute_sets_id), PRIMARY KEY(family_variant_id, variant_attribute_sets_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_association_type_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_CCCBAA2D7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_family_variant_attribute_set (id INT AUTO_INCREMENT NOT NULL, level INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_variant_attribute_set_has_attributes (variant_attribute_set_id INT NOT NULL, attributes_id INT NOT NULL, INDEX IDX_E9C4264A11D06F0E (variant_attribute_set_id), INDEX IDX_E9C4264ABAAF4009 (attributes_id), PRIMARY KEY(variant_attribute_set_id, attributes_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_variant_attribute_set_has_axes (variant_attribute_set_id INT NOT NULL, axes_id INT NOT NULL, INDEX IDX_6965051E11D06F0E (variant_attribute_set_id), INDEX IDX_6965051EE684FCEE (axes_id), PRIMARY KEY(variant_attribute_set_id, axes_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_attribute_group_translation (id INT AUTO_INCREMENT NOT NULL, foreign_key INT DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, locale VARCHAR(20) NOT NULL, INDEX IDX_B74958BD7E366551 (foreign_key), UNIQUE INDEX locale_foreign_key_idx (locale, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE pim_catalog_group_type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_693B2EF777153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE acl_classes (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_type VARCHAR(200) NOT NULL, UNIQUE INDEX UNIQ_69DD750638A36066 (class_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE acl_security_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, identifier VARCHAR(200) NOT NULL, username TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_8835EE78772E836AF85E0677 (identifier, username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE acl_object_identities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, parent_object_identity_id INT UNSIGNED DEFAULT NULL, class_id INT UNSIGNED NOT NULL, object_identifier VARCHAR(100) NOT NULL, entries_inheriting TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_9407E5494B12AD6EA000B10 (object_identifier, class_id), INDEX IDX_9407E54977FA751A (parent_object_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE acl_object_identity_ancestors (object_identity_id INT UNSIGNED NOT NULL, ancestor_id INT UNSIGNED NOT NULL, INDEX IDX_825DE2993D9AB4A6 (object_identity_id), INDEX IDX_825DE299C671CEA1 (ancestor_id), PRIMARY KEY(object_identity_id, ancestor_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE acl_entries (id INT UNSIGNED AUTO_INCREMENT NOT NULL, class_id INT UNSIGNED NOT NULL, object_identity_id INT UNSIGNED DEFAULT NULL, security_identity_id INT UNSIGNED NOT NULL, field_name VARCHAR(50) DEFAULT NULL, ace_order SMALLINT UNSIGNED NOT NULL, mask INT NOT NULL, granting TINYINT(1) NOT NULL, granting_strategy VARCHAR(30) NOT NULL, audit_success TINYINT(1) NOT NULL, audit_failure TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_46C8B806EA000B103D9AB4A64DEF17BCE4289BF4 (class_id, object_identity_id, field_name, ace_order), INDEX IDX_46C8B806EA000B103D9AB4A6DF9183C9 (class_id, object_identity_id, security_identity_id), INDEX IDX_46C8B806EA000B10 (class_id), INDEX IDX_46C8B8063D9AB4A6 (object_identity_id), INDEX IDX_46C8B806DF9183C9 (security_identity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('ALTER TABLE oro_config_value ADD CONSTRAINT FK_DAF6DF5524DB0683 FOREIGN KEY (config_id) REFERENCES oro_config (id)');
        $this->addSql('ALTER TABLE pim_api_refresh_token ADD CONSTRAINT FK_264A4510C7440455 FOREIGN KEY (client) REFERENCES pim_api_client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_api_refresh_token ADD CONSTRAINT FK_264A45108D93D649 FOREIGN KEY (user) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_api_access_token ADD CONSTRAINT FK_BD5E4023C7440455 FOREIGN KEY (client) REFERENCES pim_api_client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_api_access_token ADD CONSTRAINT FK_BD5E40238D93D649 FOREIGN KEY (user) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_datagrid_view ADD CONSTRAINT FK_B56B38F17E3C61F9 FOREIGN KEY (owner_id) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_notification_user_notification ADD CONSTRAINT FK_342AA855BF5476CA FOREIGN KEY (notification) REFERENCES pim_notification_notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_notification_user_notification ADD CONSTRAINT FK_342AA8558D93D649 FOREIGN KEY (user) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE akeneo_batch_job_execution ADD CONSTRAINT FK_62738477593D6954 FOREIGN KEY (job_instance_id) REFERENCES akeneo_batch_job_instance (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE akeneo_batch_step_execution ADD CONSTRAINT FK_BDE7D0925871C06B FOREIGN KEY (job_execution_id) REFERENCES akeneo_batch_job_execution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE akeneo_batch_warning ADD CONSTRAINT FK_8EE0AE736C7DA296 FOREIGN KEY (step_execution_id) REFERENCES akeneo_batch_step_execution (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user_access_group_role ADD CONSTRAINT FK_E7E7E38EFE54D947 FOREIGN KEY (group_id) REFERENCES oro_access_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user_access_group_role ADD CONSTRAINT FK_E7E7E38ED60322AC FOREIGN KEY (role_id) REFERENCES oro_access_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BC6ED78C3 FOREIGN KEY (file_info_id) REFERENCES akeneo_file_storage_file_info (id)');
        $this->addSql('ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BC7BBFC60C FOREIGN KEY (catalogLocale_id) REFERENCES pim_catalog_locale (id)');
        $this->addSql('ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BCA7EA8E8C FOREIGN KEY (ui_locale_id) REFERENCES pim_catalog_locale (id)');
        $this->addSql('ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BCEAA72736 FOREIGN KEY (catalogScope_id) REFERENCES pim_catalog_channel (id)');
        $this->addSql('ALTER TABLE oro_user ADD CONSTRAINT FK_F82840BCD654B1EE FOREIGN KEY (defaultTree_id) REFERENCES pim_catalog_category (id)');
        $this->addSql('ALTER TABLE oro_user_access_role ADD CONSTRAINT FK_290571BEA76ED395 FOREIGN KEY (user_id) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user_access_role ADD CONSTRAINT FK_290571BED60322AC FOREIGN KEY (role_id) REFERENCES oro_access_role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user_access_group ADD CONSTRAINT FK_EC003EF3A76ED395 FOREIGN KEY (user_id) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE oro_user_access_group ADD CONSTRAINT FK_EC003EF3FE54D947 FOREIGN KEY (group_id) REFERENCES oro_access_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_user_default_datagrid_view ADD CONSTRAINT FK_3CEEC2F2A76ED395 FOREIGN KEY (user_id) REFERENCES oro_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_user_default_datagrid_view ADD CONSTRAINT FK_3CEEC2F231518C7 FOREIGN KEY (view_id) REFERENCES pim_datagrid_view (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_channel ADD CONSTRAINT FK_E07E932A12469DE2 FOREIGN KEY (category_id) REFERENCES pim_catalog_category (id)');
        $this->addSql('ALTER TABLE pim_catalog_channel_currency ADD CONSTRAINT FK_5B55C68472F5A1AA FOREIGN KEY (channel_id) REFERENCES pim_catalog_channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_channel_currency ADD CONSTRAINT FK_5B55C68438248176 FOREIGN KEY (currency_id) REFERENCES pim_catalog_currency (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_channel_locale ADD CONSTRAINT FK_D8113CB272F5A1AA FOREIGN KEY (channel_id) REFERENCES pim_catalog_channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_channel_locale ADD CONSTRAINT FK_D8113CB2E559DFD1 FOREIGN KEY (locale_id) REFERENCES pim_catalog_locale (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_channel_translation ADD CONSTRAINT FK_8A91679D7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_model ADD CONSTRAINT FK_5943911E727ACA70 FOREIGN KEY (parent_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_model ADD CONSTRAINT FK_5943911E8A37AD0 FOREIGN KEY (family_variant_id) REFERENCES pim_catalog_family_variant (id)');
        $this->addSql('ALTER TABLE pim_catalog_category_product_model ADD CONSTRAINT FK_62B5D36B2C5DD70 FOREIGN KEY (product_model_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_category_product_model ADD CONSTRAINT FK_62B5D3612469DE2 FOREIGN KEY (category_id) REFERENCES pim_catalog_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association ADD CONSTRAINT FK_CC271001B1E1C39 FOREIGN KEY (association_type_id) REFERENCES pim_catalog_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association ADD CONSTRAINT FK_CC2710017E3C61F9 FOREIGN KEY (owner_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_group ADD CONSTRAINT FK_E91414DDEFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_group ADD CONSTRAINT FK_E91414DDFE54D947 FOREIGN KEY (group_id) REFERENCES pim_catalog_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product ADD CONSTRAINT FK_3A3A49D4EFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product ADD CONSTRAINT FK_3A3A49D44584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model ADD CONSTRAINT FK_378B82C7EFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model ADD CONSTRAINT FK_378B82C7B2C5DD70 FOREIGN KEY (product_model_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product ADD CONSTRAINT FK_91CD19C0C35E566A FOREIGN KEY (family_id) REFERENCES pim_catalog_family (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_product ADD CONSTRAINT FK_91CD19C0B2C5DD70 FOREIGN KEY (product_model_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product ADD CONSTRAINT FK_91CD19C08A37AD0 FOREIGN KEY (family_variant_id) REFERENCES pim_catalog_family_variant (id)');
        $this->addSql('ALTER TABLE pim_catalog_group_product ADD CONSTRAINT FK_7AC0C83A4584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_group_product ADD CONSTRAINT FK_7AC0C83AFE54D947 FOREIGN KEY (group_id) REFERENCES pim_catalog_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_category_product ADD CONSTRAINT FK_512179C14584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_category_product ADD CONSTRAINT FK_512179C112469DE2 FOREIGN KEY (category_id) REFERENCES pim_catalog_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_unique_data ADD CONSTRAINT FK_E0768BA34584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_unique_data ADD CONSTRAINT FK_E0768BA3B6E62EFA FOREIGN KEY (attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_model_association ADD CONSTRAINT FK_F5F4C8CAB1E1C39 FOREIGN KEY (association_type_id) REFERENCES pim_catalog_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_product_model_association ADD CONSTRAINT FK_F5F4C8CA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_group ADD CONSTRAINT FK_16EA55AEEFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_product_model_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_group ADD CONSTRAINT FK_16EA55AEFE54D947 FOREIGN KEY (group_id) REFERENCES pim_catalog_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product ADD CONSTRAINT FK_3FF3ED19EFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_product_model_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product ADD CONSTRAINT FK_3FF3ED194584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product_model ADD CONSTRAINT FK_12D4D59CEFB9C8A5 FOREIGN KEY (association_id) REFERENCES pim_catalog_product_model_association (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product_model ADD CONSTRAINT FK_12D4D59CB2C5DD70 FOREIGN KEY (product_model_id) REFERENCES pim_catalog_product_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_group_translation ADD CONSTRAINT FK_622D98DB7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_group ADD CONSTRAINT FK_5D6997EDC54C8C93 FOREIGN KEY (type_id) REFERENCES pim_catalog_group_type (id)');
        $this->addSql('ALTER TABLE pim_catalog_completeness ADD CONSTRAINT FK_113BA854E559DFD1 FOREIGN KEY (locale_id) REFERENCES pim_catalog_locale (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_completeness ADD CONSTRAINT FK_113BA85472F5A1AA FOREIGN KEY (channel_id) REFERENCES pim_catalog_channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_completeness ADD CONSTRAINT FK_113BA8544584665A FOREIGN KEY (product_id) REFERENCES pim_catalog_product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_completeness_missing_attribute ADD CONSTRAINT FK_DF61BBD3B640FBA5 FOREIGN KEY (completeness_id) REFERENCES pim_catalog_completeness (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_completeness_missing_attribute ADD CONSTRAINT FK_DF61BBD3762147F6 FOREIGN KEY (missing_attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_category ADD CONSTRAINT FK_350D8339727ACA70 FOREIGN KEY (parent_id) REFERENCES pim_catalog_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_category_translation ADD CONSTRAINT FK_1C0FA6B77E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_comment_comment ADD CONSTRAINT FK_2A32D03D727ACA70 FOREIGN KEY (parent_id) REFERENCES pim_comment_comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_comment_comment ADD CONSTRAINT FK_2A32D03DF675F31B FOREIGN KEY (author_id) REFERENCES oro_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_attribute ADD CONSTRAINT FK_492FD44FFE54D947 FOREIGN KEY (group_id) REFERENCES pim_catalog_attribute_group (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_attribute_locale ADD CONSTRAINT FK_26D2D5D0B6E62EFA FOREIGN KEY (attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_locale ADD CONSTRAINT FK_26D2D5D0E559DFD1 FOREIGN KEY (locale_id) REFERENCES pim_catalog_locale (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_option ADD CONSTRAINT FK_3DD413F8B6E62EFA FOREIGN KEY (attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_translation ADD CONSTRAINT FK_CB9A96AF7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_family_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_group_type_translation ADD CONSTRAINT FK_6EF81AEB7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_group_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family_translation ADD CONSTRAINT FK_547C9A607E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_family (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_option_value ADD CONSTRAINT FK_CC4B9A83A7C41D6F FOREIGN KEY (option_id) REFERENCES pim_catalog_attribute_option (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family ADD CONSTRAINT FK_90632072E2D3A503 FOREIGN KEY (label_attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_family ADD CONSTRAINT FK_90632072BC295696 FOREIGN KEY (image_attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE pim_catalog_family_attribute ADD CONSTRAINT FK_76074884C35E566A FOREIGN KEY (family_id) REFERENCES pim_catalog_family (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family_attribute ADD CONSTRAINT FK_76074884B6E62EFA FOREIGN KEY (attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_translation ADD CONSTRAINT FK_DBC2A9287E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement ADD CONSTRAINT FK_B494B917C35E566A FOREIGN KEY (family_id) REFERENCES pim_catalog_family (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement ADD CONSTRAINT FK_B494B917B6E62EFA FOREIGN KEY (attribute_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement ADD CONSTRAINT FK_B494B91772F5A1AA FOREIGN KEY (channel_id) REFERENCES pim_catalog_channel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family_variant ADD CONSTRAINT FK_FBA5AB45C35E566A FOREIGN KEY (family_id) REFERENCES pim_catalog_family (id)');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_has_variant_attribute_sets ADD CONSTRAINT FK_1F4DC7028A37AD0 FOREIGN KEY (family_variant_id) REFERENCES pim_catalog_family_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_has_variant_attribute_sets ADD CONSTRAINT FK_1F4DC702D8404D FOREIGN KEY (variant_attribute_sets_id) REFERENCES pim_catalog_family_variant_attribute_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_association_type_translation ADD CONSTRAINT FK_CCCBAA2D7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_association_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_attributes ADD CONSTRAINT FK_E9C4264A11D06F0E FOREIGN KEY (variant_attribute_set_id) REFERENCES pim_catalog_family_variant_attribute_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_attributes ADD CONSTRAINT FK_E9C4264ABAAF4009 FOREIGN KEY (attributes_id) REFERENCES pim_catalog_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_axes ADD CONSTRAINT FK_6965051E11D06F0E FOREIGN KEY (variant_attribute_set_id) REFERENCES pim_catalog_family_variant_attribute_set (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_axes ADD CONSTRAINT FK_6965051EE684FCEE FOREIGN KEY (axes_id) REFERENCES pim_catalog_attribute (id)');
        $this->addSql('ALTER TABLE pim_catalog_attribute_group_translation ADD CONSTRAINT FK_B74958BD7E366551 FOREIGN KEY (foreign_key) REFERENCES pim_catalog_attribute_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identities ADD CONSTRAINT FK_9407E54977FA751A FOREIGN KEY (parent_object_identity_id) REFERENCES acl_object_identities (id)');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE2993D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors ADD CONSTRAINT FK_825DE299C671CEA1 FOREIGN KEY (ancestor_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806EA000B10 FOREIGN KEY (class_id) REFERENCES acl_classes (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B8063D9AB4A6 FOREIGN KEY (object_identity_id) REFERENCES acl_object_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE acl_entries ADD CONSTRAINT FK_46C8B806DF9183C9 FOREIGN KEY (security_identity_id) REFERENCES acl_security_identities (id) ON UPDATE CASCADE ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE oro_config_value DROP FOREIGN KEY FK_DAF6DF5524DB0683');
        $this->addSql('ALTER TABLE pim_api_refresh_token DROP FOREIGN KEY FK_264A4510C7440455');
        $this->addSql('ALTER TABLE pim_api_access_token DROP FOREIGN KEY FK_BD5E4023C7440455');
        $this->addSql('ALTER TABLE pim_user_default_datagrid_view DROP FOREIGN KEY FK_3CEEC2F231518C7');
        $this->addSql('ALTER TABLE pim_notification_user_notification DROP FOREIGN KEY FK_342AA855BF5476CA');
        $this->addSql('ALTER TABLE akeneo_batch_step_execution DROP FOREIGN KEY FK_BDE7D0925871C06B');
        $this->addSql('ALTER TABLE akeneo_batch_job_execution DROP FOREIGN KEY FK_62738477593D6954');
        $this->addSql('ALTER TABLE akeneo_batch_warning DROP FOREIGN KEY FK_8EE0AE736C7DA296');
        $this->addSql('ALTER TABLE oro_user DROP FOREIGN KEY FK_F82840BC6ED78C3');
        $this->addSql('ALTER TABLE oro_user_access_group_role DROP FOREIGN KEY FK_E7E7E38EFE54D947');
        $this->addSql('ALTER TABLE oro_user_access_group DROP FOREIGN KEY FK_EC003EF3FE54D947');
        $this->addSql('ALTER TABLE oro_user_access_group_role DROP FOREIGN KEY FK_E7E7E38ED60322AC');
        $this->addSql('ALTER TABLE oro_user_access_role DROP FOREIGN KEY FK_290571BED60322AC');
        $this->addSql('ALTER TABLE pim_api_refresh_token DROP FOREIGN KEY FK_264A45108D93D649');
        $this->addSql('ALTER TABLE pim_api_access_token DROP FOREIGN KEY FK_BD5E40238D93D649');
        $this->addSql('ALTER TABLE pim_datagrid_view DROP FOREIGN KEY FK_B56B38F17E3C61F9');
        $this->addSql('ALTER TABLE pim_notification_user_notification DROP FOREIGN KEY FK_342AA8558D93D649');
        $this->addSql('ALTER TABLE oro_user_access_role DROP FOREIGN KEY FK_290571BEA76ED395');
        $this->addSql('ALTER TABLE oro_user_access_group DROP FOREIGN KEY FK_EC003EF3A76ED395');
        $this->addSql('ALTER TABLE pim_user_default_datagrid_view DROP FOREIGN KEY FK_3CEEC2F2A76ED395');
        $this->addSql('ALTER TABLE pim_comment_comment DROP FOREIGN KEY FK_2A32D03DF675F31B');
        $this->addSql('ALTER TABLE oro_user DROP FOREIGN KEY FK_F82840BC7BBFC60C');
        $this->addSql('ALTER TABLE oro_user DROP FOREIGN KEY FK_F82840BCA7EA8E8C');
        $this->addSql('ALTER TABLE pim_catalog_channel_locale DROP FOREIGN KEY FK_D8113CB2E559DFD1');
        $this->addSql('ALTER TABLE pim_catalog_completeness DROP FOREIGN KEY FK_113BA854E559DFD1');
        $this->addSql('ALTER TABLE pim_catalog_attribute_locale DROP FOREIGN KEY FK_26D2D5D0E559DFD1');
        $this->addSql('ALTER TABLE oro_user DROP FOREIGN KEY FK_F82840BCEAA72736');
        $this->addSql('ALTER TABLE pim_catalog_channel_currency DROP FOREIGN KEY FK_5B55C68472F5A1AA');
        $this->addSql('ALTER TABLE pim_catalog_channel_locale DROP FOREIGN KEY FK_D8113CB272F5A1AA');
        $this->addSql('ALTER TABLE pim_catalog_channel_translation DROP FOREIGN KEY FK_8A91679D7E366551');
        $this->addSql('ALTER TABLE pim_catalog_completeness DROP FOREIGN KEY FK_113BA85472F5A1AA');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement DROP FOREIGN KEY FK_B494B91772F5A1AA');
        $this->addSql('ALTER TABLE pim_catalog_channel_currency DROP FOREIGN KEY FK_5B55C68438248176');
        $this->addSql('ALTER TABLE pim_catalog_product_model DROP FOREIGN KEY FK_5943911E727ACA70');
        $this->addSql('ALTER TABLE pim_catalog_category_product_model DROP FOREIGN KEY FK_62B5D36B2C5DD70');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model DROP FOREIGN KEY FK_378B82C7B2C5DD70');
        $this->addSql('ALTER TABLE pim_catalog_product DROP FOREIGN KEY FK_91CD19C0B2C5DD70');
        $this->addSql('ALTER TABLE pim_catalog_product_model_association DROP FOREIGN KEY FK_F5F4C8CA7E3C61F9');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product_model DROP FOREIGN KEY FK_12D4D59CB2C5DD70');
        $this->addSql('ALTER TABLE pim_catalog_association_group DROP FOREIGN KEY FK_E91414DDEFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association_product DROP FOREIGN KEY FK_3A3A49D4EFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model DROP FOREIGN KEY FK_378B82C7EFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association DROP FOREIGN KEY FK_CC2710017E3C61F9');
        $this->addSql('ALTER TABLE pim_catalog_association_product DROP FOREIGN KEY FK_3A3A49D44584665A');
        $this->addSql('ALTER TABLE pim_catalog_group_product DROP FOREIGN KEY FK_7AC0C83A4584665A');
        $this->addSql('ALTER TABLE pim_catalog_category_product DROP FOREIGN KEY FK_512179C14584665A');
        $this->addSql('ALTER TABLE pim_catalog_product_unique_data DROP FOREIGN KEY FK_E0768BA34584665A');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product DROP FOREIGN KEY FK_3FF3ED194584665A');
        $this->addSql('ALTER TABLE pim_catalog_completeness DROP FOREIGN KEY FK_113BA8544584665A');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_group DROP FOREIGN KEY FK_16EA55AEEFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product DROP FOREIGN KEY FK_3FF3ED19EFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_product_model DROP FOREIGN KEY FK_12D4D59CEFB9C8A5');
        $this->addSql('ALTER TABLE pim_catalog_association_group DROP FOREIGN KEY FK_E91414DDFE54D947');
        $this->addSql('ALTER TABLE pim_catalog_group_product DROP FOREIGN KEY FK_7AC0C83AFE54D947');
        $this->addSql('ALTER TABLE pim_catalog_association_product_model_to_group DROP FOREIGN KEY FK_16EA55AEFE54D947');
        $this->addSql('ALTER TABLE pim_catalog_group_translation DROP FOREIGN KEY FK_622D98DB7E366551');
        $this->addSql('ALTER TABLE pim_catalog_completeness_missing_attribute DROP FOREIGN KEY FK_DF61BBD3B640FBA5');
        $this->addSql('ALTER TABLE oro_user DROP FOREIGN KEY FK_F82840BCD654B1EE');
        $this->addSql('ALTER TABLE pim_catalog_channel DROP FOREIGN KEY FK_E07E932A12469DE2');
        $this->addSql('ALTER TABLE pim_catalog_category_product_model DROP FOREIGN KEY FK_62B5D3612469DE2');
        $this->addSql('ALTER TABLE pim_catalog_category_product DROP FOREIGN KEY FK_512179C112469DE2');
        $this->addSql('ALTER TABLE pim_catalog_category DROP FOREIGN KEY FK_350D8339727ACA70');
        $this->addSql('ALTER TABLE pim_catalog_category_translation DROP FOREIGN KEY FK_1C0FA6B77E366551');
        $this->addSql('ALTER TABLE pim_comment_comment DROP FOREIGN KEY FK_2A32D03D727ACA70');
        $this->addSql('ALTER TABLE pim_catalog_product_unique_data DROP FOREIGN KEY FK_E0768BA3B6E62EFA');
        $this->addSql('ALTER TABLE pim_catalog_completeness_missing_attribute DROP FOREIGN KEY FK_DF61BBD3762147F6');
        $this->addSql('ALTER TABLE pim_catalog_attribute_locale DROP FOREIGN KEY FK_26D2D5D0B6E62EFA');
        $this->addSql('ALTER TABLE pim_catalog_attribute_option DROP FOREIGN KEY FK_3DD413F8B6E62EFA');
        $this->addSql('ALTER TABLE pim_catalog_family DROP FOREIGN KEY FK_90632072E2D3A503');
        $this->addSql('ALTER TABLE pim_catalog_family DROP FOREIGN KEY FK_90632072BC295696');
        $this->addSql('ALTER TABLE pim_catalog_family_attribute DROP FOREIGN KEY FK_76074884B6E62EFA');
        $this->addSql('ALTER TABLE pim_catalog_attribute_translation DROP FOREIGN KEY FK_DBC2A9287E366551');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement DROP FOREIGN KEY FK_B494B917B6E62EFA');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_attributes DROP FOREIGN KEY FK_E9C4264ABAAF4009');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_axes DROP FOREIGN KEY FK_6965051EE684FCEE');
        $this->addSql('ALTER TABLE pim_catalog_attribute_option_value DROP FOREIGN KEY FK_CC4B9A83A7C41D6F');
        $this->addSql('ALTER TABLE pim_catalog_association DROP FOREIGN KEY FK_CC271001B1E1C39');
        $this->addSql('ALTER TABLE pim_catalog_product_model_association DROP FOREIGN KEY FK_F5F4C8CAB1E1C39');
        $this->addSql('ALTER TABLE pim_catalog_association_type_translation DROP FOREIGN KEY FK_CCCBAA2D7E366551');
        $this->addSql('ALTER TABLE pim_catalog_attribute DROP FOREIGN KEY FK_492FD44FFE54D947');
        $this->addSql('ALTER TABLE pim_catalog_attribute_group_translation DROP FOREIGN KEY FK_B74958BD7E366551');
        $this->addSql('ALTER TABLE pim_catalog_product DROP FOREIGN KEY FK_91CD19C0C35E566A');
        $this->addSql('ALTER TABLE pim_catalog_family_translation DROP FOREIGN KEY FK_547C9A607E366551');
        $this->addSql('ALTER TABLE pim_catalog_family_attribute DROP FOREIGN KEY FK_76074884C35E566A');
        $this->addSql('ALTER TABLE pim_catalog_attribute_requirement DROP FOREIGN KEY FK_B494B917C35E566A');
        $this->addSql('ALTER TABLE pim_catalog_family_variant DROP FOREIGN KEY FK_FBA5AB45C35E566A');
        $this->addSql('ALTER TABLE pim_catalog_product_model DROP FOREIGN KEY FK_5943911E8A37AD0');
        $this->addSql('ALTER TABLE pim_catalog_product DROP FOREIGN KEY FK_91CD19C08A37AD0');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_translation DROP FOREIGN KEY FK_CB9A96AF7E366551');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_has_variant_attribute_sets DROP FOREIGN KEY FK_1F4DC7028A37AD0');
        $this->addSql('ALTER TABLE pim_catalog_family_variant_has_variant_attribute_sets DROP FOREIGN KEY FK_1F4DC702D8404D');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_attributes DROP FOREIGN KEY FK_E9C4264A11D06F0E');
        $this->addSql('ALTER TABLE pim_catalog_variant_attribute_set_has_axes DROP FOREIGN KEY FK_6965051E11D06F0E');
        $this->addSql('ALTER TABLE pim_catalog_group DROP FOREIGN KEY FK_5D6997EDC54C8C93');
        $this->addSql('ALTER TABLE pim_catalog_group_type_translation DROP FOREIGN KEY FK_6EF81AEB7E366551');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806EA000B10');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B806DF9183C9');
        $this->addSql('ALTER TABLE acl_object_identities DROP FOREIGN KEY FK_9407E54977FA751A');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE2993D9AB4A6');
        $this->addSql('ALTER TABLE acl_object_identity_ancestors DROP FOREIGN KEY FK_825DE299C671CEA1');
        $this->addSql('ALTER TABLE acl_entries DROP FOREIGN KEY FK_46C8B8063D9AB4A6');
        $this->addSql('DROP TABLE oro_config_value');
        $this->addSql('DROP TABLE oro_config');
        $this->addSql('DROP TABLE pim_api_refresh_token');
        $this->addSql('DROP TABLE pim_api_client');
        $this->addSql('DROP TABLE pim_api_auth_code');
        $this->addSql('DROP TABLE pim_api_access_token');
        $this->addSql('DROP TABLE pim_datagrid_view');
        $this->addSql('DROP TABLE pim_notification_notification');
        $this->addSql('DROP TABLE pim_notification_user_notification');
        $this->addSql('DROP TABLE pim_versioning_version');
        $this->addSql('DROP TABLE akeneo_batch_job_execution');
        $this->addSql('DROP TABLE akeneo_batch_job_instance');
        $this->addSql('DROP TABLE akeneo_batch_step_execution');
        $this->addSql('DROP TABLE akeneo_batch_warning');
        $this->addSql('DROP TABLE akeneo_batch_job_execution_queue');
        $this->addSql('DROP TABLE akeneo_file_storage_file_info');
        $this->addSql('DROP TABLE oro_access_group');
        $this->addSql('DROP TABLE oro_user_access_group_role');
        $this->addSql('DROP TABLE oro_access_role');
        $this->addSql('DROP TABLE oro_user');
        $this->addSql('DROP TABLE oro_user_access_role');
        $this->addSql('DROP TABLE oro_user_access_group');
        $this->addSql('DROP TABLE pim_user_default_datagrid_view');
        $this->addSql('DROP TABLE pim_catalog_locale');
        $this->addSql('DROP TABLE pim_catalog_channel');
        $this->addSql('DROP TABLE pim_catalog_channel_currency');
        $this->addSql('DROP TABLE pim_catalog_channel_locale');
        $this->addSql('DROP TABLE pim_catalog_channel_translation');
        $this->addSql('DROP TABLE pim_catalog_currency');
        $this->addSql('DROP TABLE pim_catalog_product_model');
        $this->addSql('DROP TABLE pim_catalog_category_product_model');
        $this->addSql('DROP TABLE pim_catalog_association');
        $this->addSql('DROP TABLE pim_catalog_association_group');
        $this->addSql('DROP TABLE pim_catalog_association_product');
        $this->addSql('DROP TABLE pim_catalog_association_product_model');
        $this->addSql('DROP TABLE pim_catalog_product');
        $this->addSql('DROP TABLE pim_catalog_group_product');
        $this->addSql('DROP TABLE pim_catalog_category_product');
        $this->addSql('DROP TABLE pim_catalog_product_unique_data');
        $this->addSql('DROP TABLE pim_catalog_product_model_association');
        $this->addSql('DROP TABLE pim_catalog_association_product_model_to_group');
        $this->addSql('DROP TABLE pim_catalog_association_product_model_to_product');
        $this->addSql('DROP TABLE pim_catalog_association_product_model_to_product_model');
        $this->addSql('DROP TABLE pim_catalog_group_translation');
        $this->addSql('DROP TABLE pim_catalog_group');
        $this->addSql('DROP TABLE pim_catalog_completeness');
        $this->addSql('DROP TABLE pim_catalog_completeness_missing_attribute');
        $this->addSql('DROP TABLE pim_catalog_category');
        $this->addSql('DROP TABLE pim_catalog_category_translation');
        $this->addSql('DROP TABLE pim_comment_comment');
        $this->addSql('DROP TABLE pim_catalog_attribute');
        $this->addSql('DROP TABLE pim_catalog_attribute_locale');
        $this->addSql('DROP TABLE pim_catalog_attribute_option');
        $this->addSql('DROP TABLE pim_catalog_family_variant_translation');
        $this->addSql('DROP TABLE pim_catalog_association_type');
        $this->addSql('DROP TABLE pim_catalog_group_type_translation');
        $this->addSql('DROP TABLE pim_catalog_family_translation');
        $this->addSql('DROP TABLE pim_catalog_attribute_group');
        $this->addSql('DROP TABLE pim_catalog_attribute_option_value');
        $this->addSql('DROP TABLE pim_catalog_family');
        $this->addSql('DROP TABLE pim_catalog_family_attribute');
        $this->addSql('DROP TABLE pim_catalog_attribute_translation');
        $this->addSql('DROP TABLE pim_catalog_attribute_requirement');
        $this->addSql('DROP TABLE pim_catalog_family_variant');
        $this->addSql('DROP TABLE pim_catalog_family_variant_has_variant_attribute_sets');
        $this->addSql('DROP TABLE pim_catalog_association_type_translation');
        $this->addSql('DROP TABLE pim_catalog_family_variant_attribute_set');
        $this->addSql('DROP TABLE pim_catalog_variant_attribute_set_has_attributes');
        $this->addSql('DROP TABLE pim_catalog_variant_attribute_set_has_axes');
        $this->addSql('DROP TABLE pim_catalog_attribute_group_translation');
        $this->addSql('DROP TABLE pim_catalog_group_type');
        $this->addSql('DROP TABLE acl_classes');
        $this->addSql('DROP TABLE acl_security_identities');
        $this->addSql('DROP TABLE acl_object_identities');
        $this->addSql('DROP TABLE acl_object_identity_ancestors');
        $this->addSql('DROP TABLE acl_entries');
    }
}
